# Generated by Django 4.2.13 on 2024-09-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0038_alter_medsupplier_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='media/videos/')),
                ('logo', models.ImageField(upload_to='media/images/')),
                ('certificate', models.ImageField(upload_to='media/images/')),
                ('company_info', models.CharField(default=None, max_length=125)),
                ('year_history', models.CharField(default=None, max_length=1000)),
                ('company_fullname', models.CharField(default=None, max_length=125)),
                ('legal_address', models.CharField(default=None, max_length=125)),
                ('RCR', models.CharField(default=None, max_length=125)),
                ('TIN', models.CharField(default=None, max_length=125)),
                ('PSRN', models.CharField(default=None, max_length=125)),
                ('bank_details', models.CharField(default=None, max_length=125)),
            ],
        ),
    ]
