# Generated by Django 4.2.13 on 2024-09-18 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0039_aboutcompany'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutcompany',
            name='company_fullname',
        ),
        migrations.RemoveField(
            model_name='aboutcompany',
            name='company_info',
        ),
    ]
