# Generated by Django 4.2.13 on 2024-09-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0040_remove_aboutcompany_company_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcompany',
            name='year_history',
            field=models.CharField(default=None, max_length=10000),
        ),
    ]
