# Generated by Django 4.2.13 on 2024-09-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0041_alter_aboutcompany_year_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcompany',
            name='certificate',
            field=models.CharField(default=None, max_length=10000),
        ),
    ]
