# Generated by Django 4.2.13 on 2024-09-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0042_alter_aboutcompany_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcompany',
            name='certificate',
            field=models.ImageField(blank=True, upload_to='media/images/'),
        ),
    ]
