# Generated by Django 4.2.13 on 2024-09-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0044_remove_aboutcompany_legal_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_message',
            field=models.CharField(default='Содержание', max_length=10000),
        ),
    ]
