# Generated by Django 4.2.13 on 2024-09-19 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0045_alter_news_news_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='MostAskedQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Содержание', max_length=200)),
                ('description', models.CharField(default='Содержание', max_length=2000)),
            ],
        ),
    ]
